name: "Activity Pub Relay CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: activity_pub_relay_test
          POSTGRES_USER: activity_pub_relay
          POSTGRES_PASSWORD: activity_pub_relay_pass
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://activity_pub_relay:activity_pub_relay_pass@localhost:5432/activity_pub_relay_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Generate key
        run bundle exec rake relay:keygen

      - name: Run tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Security audit dependencies
        run: bundle exec bundler-audit --update

      - name: Security audit application code
        run: bundle exec brakeman -q -w2

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
